### ISSUE TITLE
"Error running Solidity" on save

### ISSUE THREAD

**Issue by ghost** [Latrasis/linter-solidity#12]
Think this started when I upgraded linter-solidity (to 0.5.0), or the base linter (2.1.4), recently. Console output:
```
[Linter] Error running Solidity /Users/.../.atom/packages/linter-solidity/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global) { var Module = {"ENVIRONMENT": "NODE"};var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=true;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](filename)){filename=path.join(__dirname,"..","src",filename);ret=nodeFS["rea

TypeError: Cannot read property '0' of null
    at errors.map.err (/Users/.../.atom/packages/linter-solidity/lib/compiler.js:19:67)
    at Array.map (native)
    at parseErrors (/Users/.../.atom/packages/linter-solidity/lib/compiler.js:16:6)
    at Object.<anonymous> (/Users/.../.atom/packages/linter-solidity/lib/compiler.js:46:32)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
(anonymous function) @ /Users/.../.atom/packages/linter/lib/linter-registry.js:159
```

**Comment by ghost** [comment]
I've just had the same error for another linter, so I guess it's an error from the base linter.
