### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by msharma011** [Latrasis/linter-solidity#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [linter-solidity](https://github.com/Latrasis/linter-solidity) package 0.5.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at stdout (/packages/linter-solidity/lib/linter.js:35:24)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:219:40)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
```

### Non-Core Packages

```
color-picker 2.2.5 
language-ethereum 0.3.9 
linter 2.2.0 
linter-solidity 0.5.0 
nuclide 0.245.0 
react 0.16.2 
react-native-snippets 0.3.0 
```

**Comment by wahlforss** [comment]
This error comes up every minute... Really annoying.

**Comment by awelm** [comment]
^ I second that

**Comment by filcap** [comment]
Is there a solution for this?

**Comment by Hapovanille** [comment]
Still lost on what triggers this error, it does not happen on every file.
