### ISSUE TITLE
Failed to load the linter-solidity package

### ISSUE THREAD

**Issue by qianfei11** [Latrasis/linter-solidity#30]
I tried [`6b421ad`](https://github.com/Latrasis/linter-solidity/commit/6b421adb0bf11d5d74f817c9808808e5e12aabe5) but it didn't work.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.4
**Thrown From**: [linter-solidity](https://github.com/Latrasis/linter-solidity) package 0.5.0

### Stack Trace

Failed to load the linter-solidity package

```
At soljson.cwrap is not a function

TypeError: soljson.cwrap is not a function
    at setupMethods (/packages/linter-solidity/node_modules/solc/wrapper.js:9:29)
    at /packages/linter-solidity/node_modules/solc/index.js:3:18)
    at /packages/linter-solidity/node_modules/solc/index.js:5:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/linter-solidity/lib/linter.js:4:20)
    at /packages/linter-solidity/lib/linter.js:54:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3307234)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3293774)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3292606)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3293347)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:380859)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379282)
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:331347)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379220)
    at t.loadState.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:708769)
```

### Commands

```
  2x -9:34.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
autocomplete-solidity 0.3.4 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.0.0 
linter-solidity 0.5.0 
linter-solium 0.0.5 
linter-ui-default 1.8.0 
```

**Comment by lorenzobotticelli** [comment]
this error is annoying..

**Comment by fbalwy** [comment]
Same issue :(

**Comment by Starry1024** [comment]
annoying! 
I'm crazy now! 
Who can help me? 
Please!

**Comment by tykim42** [comment]
Same issue here too ㅡㅡ;; how can I fix it?
