### ISSUE TITLE
Failed to load the linter-solidity package

### ISSUE THREAD

**Issue by mawenpeng** [Latrasis/linter-solidity#33]
[Enter steps to reproduce:]

1. Start up Atom.
2. Install linter-solidity.
3. Restart Atom.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.4
**Thrown From**: [linter-solidity](https://github.com/Latrasis/linter-solidity) package 0.5.0

### Stack Trace

Failed to load the linter-solidity package

```
At soljson.cwrap is not a function

TypeError: soljson.cwrap is not a function
    at setupMethods (/packages/linter-solidity/node_modules/solc/wrapper.js:9:29)
    at /packages/linter-solidity/node_modules/solc/index.js:3:18)
    at /packages/linter-solidity/node_modules/solc/index.js:5:3)
    at Module.get_Module._compile (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/linter-solidity/lib/linter.js:4:20)
    at /packages/linter-solidity/lib/linter.js:54:3)
    at Module.get_Module._compile (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:1:695133)
    at Package.requireMainModule (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:3231254)
    at measure (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:3217794)
    at Package.measure (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:3216626)
    at Package.load (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:3217367)
    at PackageManager.loadAvailablePackage (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:381026)
    at config.transact (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:379449)
    at Config.transact (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:331514)
    at PackageManager.loadPackages (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:11:379387)
    at t.loadState.then (/snap/atom/248/usr/share/atom/resources/app/static/<embedded>:1:715744)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 1.1.5 
language-solidity 0.1.1 
linter 2.3.1 
linter-solidity 0.5.0 
linter-ui-default 1.8.1 
```

**Comment by imthatcarlos** [comment]
+1

**Comment by laulucky** [comment]
+1
