### ISSUE TITLE
Failed to load the linter-solidity package

### ISSUE THREAD

**Issue by MasterBaron** [Latrasis/linter-solidity#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.5
**Thrown From**: [linter-solidity](https://github.com/Latrasis/linter-solidity) package 0.5.0

### Stack Trace

Failed to load the linter-solidity package

```
At soljson.cwrap is not a function

TypeError: soljson.cwrap is not a function
    at setupMethods (/packages/linter-solidity/node_modules/solc/wrapper.js:9:29)
    at /packages/linter-solidity/node_modules/solc/index.js:3:18)
    at /packages/linter-solidity/node_modules/solc/index.js:5:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/linter-solidity/lib/linter.js:4:20)
    at /packages/linter-solidity/lib/linter.js:54:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3233575)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3220115)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3218947)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3219688)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381026)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379754)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382326)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:942215
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:936821)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125033)
```

### Commands

```
  2x -6:41 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-solidity 0.3.4 
linter-solidity 0.5.0 
```

**Comment by zhqyslna** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-solidity](https://github.com/Latrasis/linter-solidity) package 0.5.0


### Stack Trace

Failed to load the linter-solidity package

```
At soljson.cwrap is not a function

TypeError: soljson.cwrap is not a function
    at setupMethods (/packages/linter-solidity/node_modules/solc/wrapper.js:9:29)
    at /packages/linter-solidity/node_modules/solc/index.js:3:18)
    at /packages/linter-solidity/node_modules/solc/index.js:5:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/linter-solidity/lib/linter.js:4:20)
    at /packages/linter-solidity/lib/linter.js:54:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3308385)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3294925
    at Package.measure (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3293757)
    at Package.load (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3294498)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:381522)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:379945
    at Config.transact (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:332010)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:379883)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:755624
    at async Promise.all (index 0)
```

### Commands

```
```

### Non-Core Packages

```
linter-solidity 0.5.0 
```
