### ISSUE TITLE
Failed to load the linter-solidity package

### ISSUE THREAD

**Issue by Baker-Martin** [Latrasis/linter-solidity#35]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: [linter-solidity](https://github.com/Latrasis/linter-solidity) package 0.5.0

### Stack Trace

Failed to load the linter-solidity package

```
At soljson.cwrap is not a function

TypeError: soljson.cwrap is not a function
    at setupMethods (/packages/linter-solidity/node_modules/solc/wrapper.js:9:29)
    at /packages/linter-solidity/node_modules/solc/index.js:3:18)
    at /packages/linter-solidity/node_modules/solc/index.js:5:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at /packages/linter-solidity/lib/linter.js:4:20)
    at /packages/linter-solidity/lib/linter.js:54:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3204187)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3190727
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3189559)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3190300)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381522)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379945
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332010)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379883)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:716025
    at async Promise.all (index 0)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
file-icons 2.1.41 
linter-solidity 0.5.0 
```

**Comment by dougbutner** [comment]
same
