### ISSUE TITLE
Error on solidity file open

### ISSUE THREAD

**Issue by h3ph4est7s** [Latrasis/linter-solidity#5]
Greetings,
I'm getting this error when i'm opening some solidity files.

```
TypeError: Cannot read property '0' of null 
at errors.map.err (~/.atom/packages/linter-solidity/lib/compiler.js:18:67) 
at Array.map (native) 
at parseErrors (~/.atom/packages/linter-solidity/lib/compiler.js:15:6) 
at Object. (~/.atom/packages/linter-solidity/lib/compiler.js:45:32) 
at Module._compile (module.js:413:34) 
at Object.Module._extensions..js (module.js:422:10) 
at Module.load (module.js:357:32) 
at Function.Module._load (module.js:314:12) 
at Function.Module.runMain (module.js:447:10) 
at startup (node.js:154:18)
```

**Comment by Latrasis** [comment]
Should be fixed at: 5dcb586434d668. Let me know if any errors persist.

**Comment by florianporada** [comment]
Hi,
I'm getting the same error. 
Worked fine for some time and all of the sudden the error occurred.
```
TypeError: Cannot read property '0' of null 
at errors.map.err (/Users/florian/.atom/packages/linter-solidity/lib/compiler.js:19:67) 
at Array.map (native) 
at parseErrors (/Users/florian/.atom/packages/linter-solidity/lib/compiler.js:16:6) 
at Object. (/Users/florian/.atom/packages/linter-solidity/lib/compiler.js:46:32) 
at Module._compile (module.js:556:32) 
at Object.Module._extensions..js (module.js:565:10) 
at Module.load (module.js:473:32) 
at tryModuleLoad (module.js:432:12) 
at Function.Module._load (module.js:424:3) 
at Module.runMain (module.js:590:10)
```

**Comment by larslue** [comment]
Hi, I get this error when saving a solidity file. When there are errors present in the file the linter correctly outputs the errors but when the file is correct the linter-solidity packages throws the following exception:

[Linter] Error running Solidity /Users/lars/.atom/packages/linter-solidity/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname, process, global) { var Module = {"ENVIRONMENT": "NODE"};var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=true;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](filename)){filename=path.join(__dirname,"..","src",filename);ret=nodeFS["readFile

(anonymous function) @ /Users/lars/.atom/packages/linter/lib/linter-registry.js:159
